arrivals:
  N: 2001
  rate_schedule: [1, 2, 1, 2]
  start_time: "2025-01-01T00:00:00Z"
  end_time: "2026-12-31T23:59:59Z"

duration_distribution:
  type: uniform
  mean: null
  min: 18000
  std: null
  shape: null
  max: 36000

agent_availability:
  agents_in_SS: [10]