arrivals:
  N: 3001
  rate_schedule: [1,3]
  start_time: "2025-01-01T00:00:00Z"
  end_time: "2027-12-31T23:59:59Z"

duration_distribution:
  type: uniform
  mean: null
  min: 10800
  std: null
  shape: null
  max: 18000

agent_availability:
  agents_in_SS: [10]